//1st solution takes 50ms
//pay attention when to add newStr to the queue. If newStr has already been encountered before, then no need to add it!
//2nd solution takes 43ms. ref: http://blog.csdn.net/niaokedaoren/article/details/8884938


public class Solution {
    public static List<List<String>> findLadders(String start, String end, Set<String> dict) {
        dict.add(start);
        dict.add(end);
        Queue<String> queue = new LinkedList<String>();
        Map<String, Integer> minStep = new HashMap<String, Integer>();
        Map<String, List<List<String>>> minPath = new HashMap<String, List<List<String>>>();
        int len = start.length();
        queue.add(start);
        minStep.put(start, 0);
        minPath.put(start, new ArrayList<List<String>>());
        List<String> l = new ArrayList<String>();
        l.add(start);
        minPath.get(start).add(l);
        while (!queue.isEmpty()) {
            String front = queue.poll();
            if (minStep.containsKey(end) && minStep.get(front) >= minStep.get(end)) {
                break;
            }
            char[] frontc = front.toCharArray();
            for (int i = 0; i < len; i++) {
                char tmp = frontc[i];
                for (char c = 'a'; c <= 'z'; c++) {
                    if (c == tmp) {
                        continue;
                    }
                    frontc[i] = c;
                    String newStr = String.valueOf(frontc);
                    if (dict.contains(newStr) && (!minStep.containsKey(newStr) || 
                    minStep.get(newStr) == minStep.get(front)+1)) {
                        if (!minStep.containsKey(newStr)) {
                            queue.add(newStr);
                            minStep.put(newStr, minStep.get(front)+1);
                            minPath.put(newStr, new ArrayList<List<String>>());
                        }
                        for (List<String> list : minPath.get(front)) {
                            List<String> newList = new ArrayList<String>(list);
                            newList.add(newStr);
                            minPath.get(newStr).add(newList);
                        }
                    }
                }
                frontc[i] = tmp;
            }
        }
        return minPath.get(end);
    }
    public static void main(String args[]) {
        String start = "cet";
        String end = "ism";
        Set<String> dict = new HashSet<String>();
        dict.add("kid");
        dict.add("tag");
        dict.add("pup");
        dict.add("ail");
        dict.add("tun");
        dict.add("woo");
        dict.add("erg");
        dict.add("luz");
        dict.add("brr");
        dict.add("gay");
        dict.add("sip");
        dict.add("kay");
        dict.add("per");
        dict.add("val");
        dict.add("mes");
        dict.add("ohs");
        dict.add("now");
        dict.add("boa");
        dict.add("cet");
        dict.add("pal");
        dict.add("bar");
        dict.add("die");
        dict.add("war");
        dict.add("hay");
        dict.add("eco");
        dict.add("pub");
        dict.add("lob");
        dict.add("rue");
        dict.add("fry");
        dict.add("lit");
        dict.add("rex");
        dict.add("jan");
        dict.add("cot");
        dict.add("bid");
        dict.add("ali");
        dict.add("pay");
        dict.add("col");
        dict.add("gum");
        dict.add("ger");
        dict.add("row");
        dict.add("won");
        dict.add("dan");
        dict.add("rum");
        dict.add("fad");
        dict.add("tut");
        dict.add("sag");
        dict.add("yip");
        dict.add("sui");
        dict.add("ark");
        dict.add("has");
        dict.add("zip");
        dict.add("fez");
        dict.add("own");
        dict.add("ump");
        dict.add("dis");
        dict.add("ads");
        dict.add("max");
        dict.add("jaw");
        dict.add("out");
        dict.add("btu");
        dict.add("ana");
        dict.add("gap");
        dict.add("cry");
        dict.add("led");
        dict.add("abe");
        dict.add("box");
        dict.add("ore");
        dict.add("pig");
        dict.add("fie");
        dict.add("toy");
        dict.add("fat");
        dict.add("cal");
        dict.add("lie");
        dict.add("noh");
        dict.add("sew");
        dict.add("ono");
        dict.add("tam");
        dict.add("flu");
        dict.add("mgm");
        dict.add("ply");
        dict.add("awe");
        dict.add("pry");
        dict.add("tit");
        dict.add("tie");
        dict.add("yet");
        dict.add("too");
        dict.add("tax");
        dict.add("jim");
        dict.add("san");
        dict.add("pan");
        dict.add("map");
        dict.add("ski");
        dict.add("ova");
        dict.add("wed");
        dict.add("non");
        dict.add("wac");
        dict.add("nut");
        dict.add("why");
        dict.add("bye");
        dict.add("lye");
        dict.add("oct");
        dict.add("old");
        dict.add("fin");
        dict.add("feb");
        dict.add("chi");
        dict.add("sap");
        dict.add("owl");
        dict.add("log");
        dict.add("tod");
        dict.add("dot");
        dict.add("bow");
        dict.add("fob");
        dict.add("for");
        dict.add("joe");
        dict.add("ivy");
        dict.add("fan");
        dict.add("age");
        dict.add("fax");
        dict.add("hip");
        dict.add("jib");
        dict.add("mel");
        dict.add("hus");
        dict.add("sob");
        dict.add("ifs");
        dict.add("tab");
        dict.add("ara");
        dict.add("dab");
        dict.add("jag");
        dict.add("jar");
        dict.add("arm");
        dict.add("lot");
        dict.add("tom");
        dict.add("sax");
        dict.add("tex");
        dict.add("yum");
        dict.add("pei");
        dict.add("wen");
        dict.add("wry");
        dict.add("ire");
        dict.add("irk");
        dict.add("far");
        dict.add("mew");
        dict.add("wit");
        dict.add("doe");
        dict.add("gas");
        dict.add("rte");
        dict.add("ian");
        dict.add("pot");
        dict.add("ask");
        dict.add("wag");
        dict.add("hag");
        dict.add("amy");
        dict.add("nag");
        dict.add("ron");
        dict.add("soy");
        dict.add("gin");
        dict.add("don");
        dict.add("tug");
        dict.add("fay");
        dict.add("vic");
        dict.add("boo");
        dict.add("nam");
        dict.add("ave");
        dict.add("buy");
        dict.add("sop");
        dict.add("but");
        dict.add("orb");
        dict.add("fen");
        dict.add("paw");
        dict.add("his");
        dict.add("sub");
        dict.add("bob");
        dict.add("yea");
        dict.add("oft");
        dict.add("inn");
        dict.add("rod");
        dict.add("yam");
        dict.add("pew");
        dict.add("web");
        dict.add("hod");
        dict.add("hun");
        dict.add("gyp");
        dict.add("wei");
        dict.add("wis");
        dict.add("rob");
        dict.add("gad");
        dict.add("pie");
        dict.add("mon");
        dict.add("dog");
        dict.add("bib");
        dict.add("rub");
        dict.add("ere");
        dict.add("dig");
        dict.add("era");
        dict.add("cat");
        dict.add("fox");
        dict.add("bee");
        dict.add("mod");
        dict.add("day");
        dict.add("apr");
        dict.add("vie");
        dict.add("nev");
        dict.add("jam");
        dict.add("pam");
        dict.add("new");
        dict.add("aye");
        dict.add("ani");
        dict.add("and");
        dict.add("ibm");
        dict.add("yap");
        dict.add("can");
        dict.add("pyx");
        dict.add("tar");
        dict.add("kin");
        dict.add("fog");
        dict.add("hum");
        dict.add("pip");
        dict.add("cup");
        dict.add("dye");
        dict.add("lyx");
        dict.add("jog");
        dict.add("nun");
        dict.add("par");
        dict.add("wan");
        dict.add("fey");
        dict.add("bus");
        dict.add("oak");
        dict.add("bad");
        dict.add("ats");
        dict.add("set");
        dict.add("qom");
        dict.add("vat");
        dict.add("eat");
        dict.add("pus");
        dict.add("rev");
        dict.add("axe");
        dict.add("ion");
        dict.add("six");
        dict.add("ila");
        dict.add("lao");
        dict.add("mom");
        dict.add("mas");
        dict.add("pro");
        dict.add("few");
        dict.add("opt");
        dict.add("poe");
        dict.add("art");
        dict.add("ash");
        dict.add("oar");
        dict.add("cap");
        dict.add("lop");
        dict.add("may");
        dict.add("shy");
        dict.add("rid");
        dict.add("bat");
        dict.add("sum");
        dict.add("rim");
        dict.add("fee");
        dict.add("bmw");
        dict.add("sky");
        dict.add("maj");
        dict.add("hue");
        dict.add("thy");
        dict.add("ava");
        dict.add("rap");
        dict.add("den");
        dict.add("fla");
        dict.add("auk");
        dict.add("cox");
        dict.add("ibo");
        dict.add("hey");
        dict.add("saw");
        dict.add("vim");
        dict.add("sec");
        dict.add("ltd");
        dict.add("you");
        dict.add("its");
        dict.add("tat");
        dict.add("dew");
        dict.add("eva");
        dict.add("tog");
        dict.add("ram");
        dict.add("let");
        dict.add("see");
        dict.add("zit");
        dict.add("maw");
        dict.add("nix");
        dict.add("ate");
        dict.add("gig");
        dict.add("rep");
        dict.add("owe");
        dict.add("ind");
        dict.add("hog");
        dict.add("eve");
        dict.add("sam");
        dict.add("zoo");
        dict.add("any");
        dict.add("dow");
        dict.add("cod");
        dict.add("bed");
        dict.add("vet");
        dict.add("ham");
        dict.add("sis");
        dict.add("hex");
        dict.add("via");
        dict.add("fir");
        dict.add("nod");
        dict.add("mao");
        dict.add("aug");
        dict.add("mum");
        dict.add("hoe");
        dict.add("bah");
        dict.add("hal");
        dict.add("keg");
        dict.add("hew");
        dict.add("zed");
        dict.add("tow");
        dict.add("gog");
        dict.add("ass");
        dict.add("dem");
        dict.add("who");
        dict.add("bet");
        dict.add("gos");
        dict.add("son");
        dict.add("ear");
        dict.add("spy");
        dict.add("kit");
        dict.add("boy");
        dict.add("due");
        dict.add("sen");
        dict.add("oaf");
        dict.add("mix");
        dict.add("hep");
        dict.add("fur");
        dict.add("ada");
        dict.add("bin");
        dict.add("nil");
        dict.add("mia");
        dict.add("ewe");
        dict.add("hit");
        dict.add("fix");
        dict.add("sad");
        dict.add("rib");
        dict.add("eye");
        dict.add("hop");
        dict.add("haw");
        dict.add("wax");
        dict.add("mid");
        dict.add("tad");
        dict.add("ken");
        dict.add("wad");
        dict.add("rye");
        dict.add("pap");
        dict.add("bog");
        dict.add("gut");
        dict.add("ito");
        dict.add("woe");
        dict.add("our");
        dict.add("ado");
        dict.add("sin");
        dict.add("mad");
        dict.add("ray");
        dict.add("hon");
        dict.add("roy");
        dict.add("dip");
        dict.add("hen");
        dict.add("iva");
        dict.add("lug");
        dict.add("asp");
        dict.add("hui");
        dict.add("yak");
        dict.add("bay");
        dict.add("poi");
        dict.add("yep");
        dict.add("bun");
        dict.add("try");
        dict.add("lad");
        dict.add("elm");
        dict.add("nat");
        dict.add("wyo");
        dict.add("gym");
        dict.add("dug");
        dict.add("toe");
        dict.add("dee");
        dict.add("wig");
        dict.add("sly");
        dict.add("rip");
        dict.add("geo");
        dict.add("cog");
        dict.add("pas");
        dict.add("zen");
        dict.add("odd");
        dict.add("nan");
        dict.add("lay");
        dict.add("pod");
        dict.add("fit");
        dict.add("hem");
        dict.add("joy");
        dict.add("bum");
        dict.add("rio");
        dict.add("yon");
        dict.add("dec");
        dict.add("leg");
        dict.add("put");
        dict.add("sue");
        dict.add("dim");
        dict.add("pet");
        dict.add("yaw");
        dict.add("nub");
        dict.add("bit");
        dict.add("bur");
        dict.add("sid");
        dict.add("sun");
        dict.add("oil");
        dict.add("red");
        dict.add("doc");
        dict.add("moe");
        dict.add("caw");
        dict.add("eel");
        dict.add("dix");
        dict.add("cub");
        dict.add("end");
        dict.add("gem");
        dict.add("off");
        dict.add("yew");
        dict.add("hug");
        dict.add("pop");
        dict.add("tub");
        dict.add("sgt");
        dict.add("lid");
        dict.add("pun");
        dict.add("ton");
        dict.add("sol");
        dict.add("din");
        dict.add("yup");
        dict.add("jab");
        dict.add("pea");
        dict.add("bug");
        dict.add("gag");
        dict.add("mil");
        dict.add("jig");
        dict.add("hub");
        dict.add("low");
        dict.add("did");
        dict.add("tin");
        dict.add("get");
        dict.add("gte");
        dict.add("sox");
        dict.add("lei");
        dict.add("mig");
        dict.add("fig");
        dict.add("lon");
        dict.add("use");
        dict.add("ban");
        dict.add("flo");
        dict.add("nov");
        dict.add("jut");
        dict.add("bag");
        dict.add("mir");
        dict.add("sty");
        dict.add("lap");
        dict.add("two");
        dict.add("ins");
        dict.add("con");
        dict.add("ant");
        dict.add("net");
        dict.add("tux");
        dict.add("ode");
        dict.add("stu");
        dict.add("mug");
        dict.add("cad");
        dict.add("nap");
        dict.add("gun");
        dict.add("fop");
        dict.add("tot");
        dict.add("sow");
        dict.add("sal");
        dict.add("sic");
        dict.add("ted");
        dict.add("wot");
        dict.add("del");
        dict.add("imp");
        dict.add("cob");
        dict.add("way");
        dict.add("ann");
        dict.add("tan");
        dict.add("mci");
        dict.add("job");
        dict.add("wet");
        dict.add("ism");
        dict.add("err");
        dict.add("him");
        dict.add("all");
        dict.add("pad");
        dict.add("hah");
        dict.add("hie");
        dict.add("aim");
        dict.add("ike");
        dict.add("jed");
        dict.add("ego");
        dict.add("mac");
        dict.add("baa");
        dict.add("min");
        dict.add("com");
        dict.add("ill");
        dict.add("was");
        dict.add("cab");
        dict.add("ago");
        dict.add("ina");
        dict.add("big");
        dict.add("ilk");
        dict.add("gal");
        dict.add("tap");
        dict.add("duh");
        dict.add("ola");
        dict.add("ran");
        dict.add("lab");
        dict.add("top");
        dict.add("gob");
        dict.add("hot");
        dict.add("ora");
        dict.add("tia");
        dict.add("kip");
        dict.add("han");
        dict.add("met");
        dict.add("hut");
        dict.add("she");
        dict.add("sac");
        dict.add("fed");
        dict.add("goo");
        dict.add("tee");
        dict.add("ell");
        dict.add("not");
        dict.add("act");
        dict.add("gil");
        dict.add("rut");
        dict.add("ala");
        dict.add("ape");
        dict.add("rig");
        dict.add("cid");
        dict.add("god");
        dict.add("duo");
        dict.add("lin");
        dict.add("aid");
        dict.add("gel");
        dict.add("awl");
        dict.add("lag");
        dict.add("elf");
        dict.add("liz");
        dict.add("ref");
        dict.add("aha");
        dict.add("fib");
        dict.add("oho");
        dict.add("tho");
        dict.add("her");
        dict.add("nor");
        dict.add("ace");
        dict.add("adz");
        dict.add("fun");
        dict.add("ned");
        dict.add("coo");
        dict.add("win");
        dict.add("tao");
        dict.add("coy");
        dict.add("van");
        dict.add("man");
        dict.add("pit");
        dict.add("guy");
        dict.add("foe");
        dict.add("hid");
        dict.add("mai");
        dict.add("sup");
        dict.add("jay");
        dict.add("hob");
        dict.add("mow");
        dict.add("jot");
        dict.add("are");
        dict.add("pol");
        dict.add("arc");
        dict.add("lax");
        dict.add("aft");
        dict.add("alb");
        dict.add("len");
        dict.add("air");
        dict.add("pug");
        dict.add("pox");
        dict.add("vow");
        dict.add("got");
        dict.add("meg");
        dict.add("zoe");
        dict.add("amp");
        dict.add("ale");
        dict.add("bud");
        dict.add("gee");
        dict.add("pin");
        dict.add("dun");
        dict.add("pat");
        dict.add("ten");
        dict.add("mob");
        long startTime = System.currentTimeMillis();
        findLadders(start, end, dict);
        long endTime = System.currentTimeMillis();
        System.out.println(endTime - startTime);
    }
}

//2nd Solution 43ms
    public static List<List<String>> findLadders(String start, String end, Set<String> dict) {
        dict.add(start);
        dict.add(end);
        Queue<String> queue = new LinkedList<String>();
        Map<String, Integer> minStep = new HashMap<String, Integer>();
        Map<String, Set<String>> prev = new HashMap<String, Set<String>>();
        int len = start.length();
        queue.add(start);
        minStep.put(start, 0);
        while (!queue.isEmpty()) {
            String front = queue.poll();
            if (minStep.containsKey(end) && minStep.get(front) >= minStep.get(end)) {
                break;
            }
            char[] frontc = front.toCharArray();
            for (int i = 0; i < len; i++) {
                char tmp = frontc[i];
                for (char c = 'a'; c <= 'z'; c++) {
                    if (c == tmp) {
                        continue;
                    }
                    frontc[i] = c;
                    String newStr = String.valueOf(frontc);
                    if (dict.contains(newStr) && (!minStep.containsKey(newStr) || 
                    minStep.get(newStr) == minStep.get(front)+1)) {
                        if (!minStep.containsKey(newStr)) {
                            queue.add(newStr);
                            minStep.put(newStr, minStep.get(front)+1);
                            prev.put(newStr, new HashSet<String>());
                        }
                        prev.get(newStr).add(front);
                    }
                }
                frontc[i] = tmp;
            }
        }
        List<List<String>> res = new ArrayList<List<String>>();
        List<String> path = new ArrayList<String>();
        path.add(end);
        return res;
    }
    public void backTracking(Map<String, Set<String>> prev, String str, 
    String start, List<String> path, List<List<String>> res) {
        if (str.equals(start)) {
            res.add(new ArrayList<String>(path));
            return;
        }
        for (String s : prev.get(str)) {
            path.add(0, s);
            backTracking(prev, s, start, path, res);
            path.remove(0);
        }
    }
